"""tool.create_draft — Create a scheduled draft in Typefully (X). Call once per post.

Generated by adl build. Do not edit.

Binding: runtime stub — the implementation is user code.
"""
import os
import urllib
import json
from langchain.tools import tool


@tool
def create_draft(
    content: str,
    publish_at: str = "next-free-slot",
) -> str:
    """Create a scheduled draft in Typefully (X). Call once per post.

    Args:
        content: The post text, verbatim. For a thread, separate tweets with four consecutive newlines.
        publish_at: ISO 8601 datetime with timezone (e.g. 2026-07-10T09:00:00Z), or 'next-free-slot'
    """
    api_key = os.environ["TYPEFULLY_API_KEY"]
    social_set_id = os.environ["TYPEFULLY_SOCIAL_SET_ID"]

    # Four consecutive newlines = thread separator (Typefully convention).
    posts = [{"text": part.strip()} for part in content.split("\n\n\n\n") if part.strip()]

    body = {
        "platforms": {"x": {"enabled": True, "posts": posts}},
        "publish_at": publish_at,
    }

    req = urllib.request.Request(
        f"https://api.typefully.com/v2/social-sets/{social_set_id}/drafts",
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read().decode("utf-8"))

    return (
        f"Draft {result.get('id')} created, "
        f"scheduled_date={result.get('scheduled_date') or publish_at}"
    )
